### ISSUE TITLE
Unable to select existing features to update attributes

### ISSUE THREAD

**Issue by dqhntb** [doug-m/CollectorAuroraTesting#178] opened 2018-10-02 19:04 UTC
### Issue
Was unable to select existing points to update in Aurora build 2440 during holistic testing but using the same map, was able to select existing points to update attributes, location etc.   Only able to select non-editable layer in my map to see pop up info via map tapping.

### Expected Behavior
Trying to tap on existing point or get to the crosshairs necessary to update its information and attributes.

### Map and Credentials

* Group Name: not shared to group
* Map Name: https://hntbcorp.maps.arcgis.com/home/webmap/viewer.html?webmap=c7fe3ddddcbb43289333698b7b26cf70

### Steps to Reproduce
Do you I need to share this content item for the Collector Esri team to test?

### Device Information
* Device: iPad Mini 4
* OS Version: IOS12

**Comment by doug-m** [comment] 2018-10-02 20:30
@dqhntb can you share this map (and services) to a group and invite the Collector4ArcGIS user to the group so we can review?

**Comment by dqhntb** [comment] 2018-10-03 13:05
I now sent an invitation to Collector4ArcGIS to a public group in our ArcGIS online organization

**Comment by doug-m** [comment] 2018-10-03 14:53
@dqhntb thanks.  Can you confirm the affected features are from the `AGOEditorTest4` layer?

**Comment by doug-m** [comment] 2018-10-03 19:03
SF 1237

**Comment by dqhntb** [comment] 2018-10-03 19:09
Hi @doug-m - are you seeing the same behavior and is this a bug for this particular point layer?

**Comment by doug-m** [comment] 2018-10-03 19:12
Yes, can reproduce.  Seems to be specific to this point layer - we will need to investigate further.

**Comment by doug-m** [comment] 2018-10-30 14:49
@dqhntb it appears there is an issue with this specific popup definition on a date field.  This is the underlying cause; we are working with others within development to assess how this may have been generated. 

In the meantime, you should be able to update the popup in your web map to define a time format, and save the map to work around this issue.

**Comment by Kevin-GIS** [comment] 2019-03-13 16:59
Closing this issue as the original behavior was due to an invalid date format in the JSON of the feature service. Further testing wasn't able to reproduce this issue outside of manually modifying the JSON to replicate the original issue.

Will reopen this issue if this behavior is still reproducible. Will require more details about specifically how this data was originally created and published or if any customization's were performed on it.

**Closed by Kevin-GIS** 2019-03-13 16:59 UTC
Labels: A-bug, B - In Product Plan, iOS
