### ISSUE TITLE
"No collectable layers are visible" persists inaccurately

### ISSUE THREAD

**Issue by btpschroeder** [doug-m/CollectorAuroraTesting#108] opened 2018-06-18 19:16 UTC
### Issue
I am unable to view the editing template for collecting data in the feature list. No amount of panning or zooming makes the ""No collectable layers are visible" message disappear.

### Expected Behavior

The bottom dialog should populate with layers.

### Map and Credentials

Unable to provide direct access, but am happy to share any metadata or information you might need. The items are hosted on a Portal, and both the web map extent and feature layer extent include the area in which I am working.

### Steps to Reproduce
N/A

### Device Information
* Device: iPhone 8 (64 GB)
* OS Version: iOS 11.4

![holistic-no-layers](https://user-images.githubusercontent.com/19781811/41557073-85fe6716-730a-11e8-95cb-2e67e7090966.png)

**Comment by Kevin-GIS** [comment] 2018-06-18 19:21
Might be similar/related to SF 912. However the workaround doesn't apply. So the underlying issue might be different.

**Comment by btpschroeder** [comment] 2018-06-18 21:03
I strongly suspect this is related to the layer and not the web map. After doing further testing, some feature layers are working properly while others aren't -- and the ones that _don't_ work are all being generated the same way. I'm attaching the layer JSON should that be useful.

``{
 "currentVersion": 10.51,
 "id": 0,
 "name": "COLLECTOR",
 "type": "Feature Layer",
 "displayField": "objectid",
 "description": "",
 "copyrightText": "",
 "defaultVisibility": true,
 "editingInfo": {"lastEditDate": 1509125957490},
 "relationships": null,
 "isDataVersioned": false,
 "supportsCalculate": true,
 "supportsAttachmentsByUploadId": false,
 "supportsRollbackOnFailureParameter": true,
 "supportsStatistics": true,
 "supportsAdvancedQueries": true,
 "supportsValidateSql": true,
 "supportsCoordinatesQuantization": false,
 "advancedQueryCapabilities": {
  "supportsReturningQueryExtent": true,
  "supportsStatistics": true,
  "supportsDistinct": true,
  "supportsPagination": true,
  "supportsOrderBy": true,
  "supportsQueryWithDistance": true,
  "supportsLod": false,
  "supportsPaginationOnAggregatedQueries": true,
  "supportsQueryWithResultType": true
 },
 "geometryType": "esriGeometryPoint",
 "minScale": 0,
 "maxScale": 0,
 "extent": {
  "xmin": -1.5399920962667E7,
  "ymin": 675091.8338144557,
  "xmax": -5615981.342167039,
  "ymax": 8502243.530214423,
  "spatialReference": {
   "latestWkid": 3857,
   "wkid": 102100
  }
 },
 "drawingInfo": {
  "renderer": {
   "type": "simple",
   "symbol": {
    "type": "esriPMS",
    "url": "500274bf-c419-48f7-8ead-99193f3f1d13",
    "imageData": "iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAOlJREFUGJV10LFLAnEYxvFvciCCnvKDGxpCkMZoEYIEHdQCB3HVyakU2lpqa2lrEAQRl6ZoaHBx7g9o0EnyGtyEhurF5YiDQx1+Knegz/TA+3nf4TUIJs49OSwivDJmyOdmYGyKelF1J+vcukfuKQfAFT988MYFd4Cj4TNlqUibKOb2dgyLIje8Y1CgqWGa6wDy54waDbrGevtkJwKIYqq8ymi4xNsLl4CHp6EwIsXxTvjNr0ykr+GUByyyJDkMIIdF2A633Ef3T8MqNgMumfNEgnNCRPjnS81URwrSA98fKTMGSv6Dgmz7CpN6Ogm2gMtkAAAAAElFTkSuQmCC",
    "contentType": "image/png",
    "width": 7,
    "height": 7,
    "angle": 0,
    "xoffset": 0,
    "yoffset": 0
   },
   "label": "",
   "description": "Location tracking log for ArcGIS Collector app."
  },
  "transparency": 0,
  "labelingInfo": null
 },
 "allowGeometryUpdates": true,
 "hasAttachments": false,
 "htmlPopupType": "esriServerHTMLPopupTypeAsHTMLText",
 "hasM": false,
 "hasZ": false,
 "objectIdField": "objectid",
 "globalIdField": "globalid",
 "typeIdField": "",
 "fields": [
  {
   "name": "objectid",
   "type": "esriFieldTypeOID",
   "alias": "OBJECTID",
   "nullable": false,
   "editable": false,
   "domain": null
  },
  {
   "name": "notes",
   "type": "esriFieldTypeString",
   "alias": "notes",
   "editable": true,
   "length": 1024,
   "nullable": true
  },
  {
   "name": "created_user",
   "type": "esriFieldTypeString",
   "alias": "created_user",
   "editable": false,
   "length": 1024,
   "nullable": true
  },
  {
   "name": "created_date",
   "type": "esriFieldTypeDate",
   "alias": "created_date",
   "editable": false,
   "length": 29,
   "nullable": true
  },
  {
   "name": "last_edited_user",
   "type": "esriFieldTypeString",
   "alias": "last_edited_user",
   "editable": false,
   "length": 1024,
   "nullable": true
  },
  {
   "name": "last_edited_date",
   "type": "esriFieldTypeDate",
   "alias": "last_edited_date",
   "editable": false,
   "length": 29,
   "nullable": true
  },
  {
   "name": "int",
   "type": "esriFieldTypeInteger",
   "alias": "int",
   "editable": true,
   "nullable": true
  },
  {
   "name": "double",
   "type": "esriFieldTypeDouble",
   "alias": "double",
   "editable": true,
   "nullable": true
  },
  {
   "name": "date",
   "type": "esriFieldTypeDate",
   "alias": "date",
   "editable": true,
   "length": 29,
   "nullable": true
  },
  {
   "alias": "globalid",
   "name": "globalid",
   "length": 38,
   "domain": null,
   "nullable": false,
   "type": "esriFieldTypeGlobalID",
   "editable": false
  }
 ],
 "supportedQueryFormats": "JSON, geoJSON",
 "hasStaticData": false,
 "maxRecordCount": 1000,
 "capabilities": "Create,Editing,Query,Update,Uploads,Delete,Sync",
 "syncEnabled": true,
 "editFieldsInfo": {
  "creationDateField": "created_date",
  "creatorField": "created_user",
  "editDateField": "last_edited_date",
  "editorField": "last_edited_user"
 },
 "allowUpdateWithoutMValues": true,
 "syncCanReturnChanges": true,
 "supportsValidateSQL": true,
 "useStandardizedQueries": true,
 "supportsApplyEditsWithGlobalIds": true,
 "types": [],
 "templates": [],
 "timeInfo": {
  "startTimeField": "created_date",
  "endTimeField": null,
  "trackIdField": null,
  "timeReference": {
   "timeZone": "UTC",
   "respectsDaylightSaving": false
  },
  "timeInterval": 0,
  "timeIntervalUnits": null,
  "exportOptions": {
   "useTime": false,
   "timeDataCumulative": false,
   "timeOffset": 0,
   "timeOffsetUnits": "esriTimeUnitsCenturies"
  },
  "hasLiveData": true,
  "timeExtent": [
   1509126300000,
   1509126420000
  ]
 },
 "standardMaxRecordCount": 16000,
 "tileMaxRecordCount": 4000,
 "maxRecordCountFactor": 1,
 "serviceItemId": "df111a6cb91c4d60af8c9fb9d5bc75a6"
}``

**Comment by Kevin-GIS** [comment] 2018-06-19 19:36
@btpschroeder what version of Portal are you working with?

Is that a hosted feature service or a federated feature service?

**Comment by Kevin-GIS** [comment] 2018-06-19 19:39
@btpschroeder it tested with my 10.6 portal hosted feature service layer/map and I couldn't reproduce the issue. I would like to compare our services together if possible. Is it possible for you to create a test user account so that I can gain access to that map to test with?

**Comment by btpschroeder** [comment] 2018-06-19 23:35
@Kevin-GIS All of our layers are hosted feature layers. Our test Portal is on 10.5.1. I'll contact the team and see what I can share with you... would be nice to give you as much access as possible so we can figure out what's causing this in Aurora. I'll follow up.

**Comment by Kevin-GIS** [comment] 2018-06-20 16:56
Hi @btpschroeder I have been able to reproduce the issue you're seeing with that particular map/service, using the account you shared.

I understand that its using a Location Tracking layer, but how was it originally created? Was it created using this method https://www.arcgis.com/home/item.html?id=051146f34aec4ef8ac228b5e6b2b8eac or generated from a layer template directly inside Portal?

I am not seeing this issue using another one of my maps that has a Location Tracking layer in it. 
 
The 'Time Info' section of the JSON is formatted slightly differently between both services, therefore that might be where the issue is. However, that could also be due to the version of Portal being used vs AGOL. 

Is this the only map that you're having this issue with?

**Comment by Kevin-GIS** [comment] 2018-08-16 19:32
Closing as non-reproducible. This behavior has been addressed in SF 922.

**Closed by Kevin-GIS** 2018-08-16 19:32 UTC
Labels: A-bug, B - Dev Review
