### ISSUE TITLE
High Accuracy Collection Differences Issue - Collector vs. Aurora

### ISSUE THREAD

**Issue by ratliffk** [doug-m/CollectorAuroraTesting#141] opened 2018-06-19 15:26 UTC
### Issue
There is a 6.04 foot horizontal difference in the same spot collected between current production Collector compared to Aurora.

### Expected Behavior
The spot collected should be within a centimeter or less when collected with production Collector or Aurora.  The difference is 6.04 feet as shown in the attachment.  The question mark icons are Aurora. The "w" and plus sign icons were collected in production Collector at the same time.

### Map and Credentials

* Group Name:
* Map Name:

Collect and compare the same location with both applications.  Evaluation shown is within ArcGIS Desktop.

### Device Information
* Device: Apple iPad
* OS Version: iOS Version 11.3.1
![aurora_collector accuracy error](https://user-images.githubusercontent.com/40370642/41607205-7952b496-73b3-11e8-9067-d7371aadfe54.jpg)

**Comment by Kevin-GIS** [comment] 2018-06-27 19:18
Thanks for the feedback @ratliffk 

I reproduced this issue and logged SF 895

**Comment by Kevin-GIS** [comment] 2018-07-02 23:56
@ratliffk can you still reproduce this issue using build 2286 of Aurora? 

I tested this issue using that build and I cannot reproduce it. Both the RTK locations from the current version of Collector and Aurora matched.

**Comment by ratliffk** [comment] 2018-07-03 13:59
@Kevin-GIS I will try to do so before the end of this week.  Thanks for the update.  Will advise results.

**Comment by Kevin-GIS** [comment] 2018-07-18 17:35
Hi @ratliffk 

I just wanted to follow-up to see if you had a chance to test this out on your end with the latest beta version? 

Are you still seeing this shifting issue?

Thanks

**Comment by Kevin-GIS** [comment] 2018-09-20 21:28
Also SF 1176

**Comment by Kevin-GIS** [comment] 2018-10-02 00:03
This issue has been addressed. Closing this issue.

**Closed by Kevin-GIS** 2018-10-02 00:03 UTC
Labels: A-bug, B - In Product Plan
