### ISSUE TITLE
Zooming really far out when defining offline area freezes Collector

### ISSUE THREAD

**Issue by mschenker** [doug-m/CollectorAuroraTesting#149] opened 2018-06-19 18:43 UTC
### Issue
When defining an (ad-hoc) offline area in Collector, zooming really far out (with LOD set to the default) results in the Collector freezing and not responding anymore.
It does not recover, even after several minutes. Only way to cancel out is restarting the app.

### Map and Credentials

I tested this on several maps, all with the same result (in the productive AGOL system), one example is the following: 
* Group Name: EsriSwitzerland2AuroraHolistic
* Map Name: SwissImageÖÜä2

### Steps to Reproduce
Open Webmap in Collector, go to "Add Offline Area" , zoom as far out as possible

### Device Information
* Device: iPad Mini 4
* OS Version: 11.3.1

**Comment by Kevin-GIS** [comment] 2018-06-25 22:32
This issue isn't reproducible in the next Beta version. 

Closing this issue since it will be addressed in the next Beta release version.

**Closed by Kevin-GIS** 2018-06-25 22:32 UTC
Labels: A-bug, B - Dev Review
