### ISSUE TITLE
Default basemap disappears after you switch basemaps in offline use

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#55] opened 2018-04-05 21:43 UTC
### Issue

Related to other problems I am seeing with offline use in Collector-- the option to switch basemaps is available, which is strange in offline use. A problem associated with this is that if you have selected to look at another basemap for an offline area, if you go back to the default basemap, this stays white and the tiles are never returned again. Any subsequent offline areas you delete will also display this problem and restarting the app does not fix it.

### Expected Behavior

I would expect to be able to view the default basemap again

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce

1) Create a sync enabled feature service and add to a web map; download for offline use
2) Click the ... icon > Basemaps > Switch basemaps 
3) Go back to the default basemap now; white tiles are always returned.
4) If you delete the offline area and re-download it, this does not resolve the issue. Restarting the app does not resolve the issue

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by mschenker** [comment] 2018-04-06 14:30
Could be the same as #40

**Comment by Kevin-GIS** [comment] 2018-04-20 18:29
Closing as a duplicate of https://github.com/doug-m/CollectorAuroraTesting/issues/58

**Closed by Kevin-GIS** 2018-04-20 18:29 UTC
Labels: A-bug
