### ISSUE TITLE
Entering a value outside of a range domain crashes the app

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#160] opened 2018-08-21 21:14 UTC
### Issue
I have set up a range domain for a numeric field. Entering a value outside of the range domain crashes the app when attempting to jump to the next field (or save value). A warning in red text does appear that the value is out of range.

### Expected Behavior
We should only see the warning message

### Map and Credentials

* Group Name: Collector Holostic 8/21
* Map Name: WollyStar_Aurora

### Steps to Reproduce

1. Set up a range domain on a numeric field (short) or use the above data
2. Attempt to enter a value outside of the accepted range, in this case 0-10. You will see the warning message in red text
3. Click 'next' or in another field and the app will crash

### Device Information
* Device: iphone 6
* OS Version: 11.4.1

[RangeDomain_Crash.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2308082/RangeDomain_Crash.zip)

**Comment by Kevin-GIS** [comment] 2018-08-22 19:40
@colinlawr I am unable to reproduce this issue. Can you reproduce this crash each time?

Could you please capture a video of the workflow on the phone and attach it to this issue?

**Comment by colinlawr** [comment] 2018-08-22 19:50
@Kevin-GIS I cant reproduce this today. Perhaps it was specific to one of the offline areas I removed. I only saved the log yesterday and not a video. I will give this another shot later.

**Comment by Kevin-GIS** [comment] 2018-10-02 00:01
Unable to reproduce the crash in the latest Beta build 2437. Closing this issue.

**Closed by Kevin-GIS** 2018-10-02 00:01 UTC
Labels: A-bug, B - Dev Review
