### ISSUE TITLE
Switching iPad Receiver and Provider Settings

### ISSUE THREAD

**Issue by ratliffk** [doug-m/CollectorAuroraTesting#118] opened 2018-06-18 20:38 UTC
### Issue
Currently in the Aurora beta, I've connected the EOS Arrow device to an iPad.  When not connected and working in Aurora, I change back to the Integrated Receiver.  Upon reconnect to the Arrow, I have I'm able to change the provider, but it drops the Profile each time.  Meaning I have to look up three pieces of information to assure function.

### Expected Behavior
When selecting a previous used Provider setting (in this case EOS Arrow versus the Integrated Receiver), the previously used "EOS" Profile settings should be available for selection.

Currently, the profile has to be recreated each time.

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
Open Collector.  Check the Provider setting to confirm Integrated Receiver.  Close window.
Check Profile to confirm Default is selected.
Connect EOS Arrow Gold receiver.  Change the Provider to EOS Positioning.  Close window.
Open Profile, create the required coordinate system, datum and projection settings.
Use Collector.
Disconnect EOS from Collector.
Change back the Provider to Integrated Receiver, Profile to Default.
Use Collector.
Close map, open settings, follow steps above to connect and setup EOS.
Finding the Provider is still listed, but the Profile has to be reset each time.

### Device Information
* Device:  Apple iPad
* OS Version:  iOS Version 11.3.1

**Comment by Kevin-GIS** [comment] 2018-06-22 16:13
@ratliffk with regards to the repro steps listed above, when you say 'Disconnect EOS from Collector', how are you disconnecting it? Just turning the receiver off, removing from the Bluetooth connections via the device settings, etc.

**Comment by ratliffk** [comment] 2018-06-22 18:15
@Kevin-GIS - typically by powering the EOS device off.  Bluetooth may or may not be turned off in the iPad settings.

**Comment by ratliffk** [comment] 2018-06-22 18:22
Kenny Ratliff
GIS Manager
[OCWD_colorsmall]
2160 Spencer Court
La Grange, Kentucky 40031
Office – 502.222.1690
Cell – 502.443.5621

**Comment by Kevin-GIS** [comment] 2018-06-26 17:04
Thanks for information @ratliffk. I am having difficulty reproducing this behavior. 

Would it be possible for you to share a screen recording of your steps? This will help me to ensure I am following the same procedure correctly.

**Comment by ratliffk** [comment] 2018-07-03 14:06
@Kevin-GIS sorry for the delay in responding.  Yes, I will try to capture the steps in a recording.  Hopefully by the end of the week. Thanks for your patience!

**Comment by Kevin-GIS** [comment] 2018-10-02 00:09
Unable to reproduce in the current Beta version. Closing this issue.

**Closed by Kevin-GIS** 2018-10-02 00:09 UTC
Labels: A-bug, B - Dev Review
