### ISSUE TITLE
Internal GPS doesn't work after switching from external GNSS reciever to internal

### ISSUE THREAD

**Issue by xavierjunod** [doug-m/CollectorAuroraTesting#207] opened 2018-10-04 15:14 UTC
### Issue
Internal GPS doesn't work after switching from external GNSS reciever to internal. 

Tested with Trimble R1 and EoS Arrow Gold (directly connected to Collector, no third party apps involved). 

### Expected Behavior

Collector should be able to switch between external and internal GPS without the need to reload the map.  Switching from Internal to external works fine and reloading the map is not needed.  

### Map and Credentials
Not data specific

### Steps to Reproduce

1. Connect an external GNSS reciever to collector (directly connected to Collector, no third party apps involved)
2.  Open a map
3. Go back to the main menu and switch from external GPS to internal
4. Go back to the map, not that the internal GPS is not working. The message at the top of the screens says " GPS Location not Available"

To solve the issue: 
- in online mode: hit the "Reload map" button
- in offline mode:  open another offline map area, when re-open the map area with the issue. If there is only 1 off-line map area in on the device, reboot collector.

### Device Information
* Device: iPad pro, Trimble R1 and EoS Arrow Gold  GNSS recievers
* OS Version: iOS11

**Comment by Kevin-GIS** [comment] 2018-10-04 17:46
@xavierjunod thanks for feedback. 

After switching from the external receiver back to the integrated receiver, when the map opens, have you tried just clicking on the GPS tool icon? (the arrow button in the map display). That should reconnect the receiver.

**Comment by Kevin-GIS** [comment] 2018-10-31 23:48
@xavierjunod I just wanted to follow-up to see if this is still an issue you're running into, based off my last comment?

**Comment by Kevin-GIS** [comment] 2018-12-28 22:13
Unable to reproduce this issue. Closing for now. Will reopen if it's still a problem.

**Closed by Kevin-GIS** 2018-12-28 22:13 UTC
Labels: A-bug, B - Dev Review
