### ISSUE TITLE
Switching from offline area to another basemap only works in one direction

### ISSUE THREAD

**Issue by mschenker** [doug-m/CollectorAuroraTesting#40] opened 2018-04-05 19:55 UTC
### Issue
It is possible to switch from an offline basemap (an offline area) to another basemap by opening the "Basemap" pane. It is however not possible to switch back to the offline area (called "Default" in the pane) after this switch, it will just display a grey background. It is only possible to switch back to the offline map (offline area) after switching to another webmap.

### Expected Behavior
It should be possible to switch back to the original offline basemap.
Additionally, the following would also be helpful:
- It should be possible to switch to another basemap and take it offline in addition to the first one
- It should be possible to switch to a basemap (basemap of another webmap) that was already previously taken offline or sideloaded, at least if it has the same projection.

### Steps to Reproduce
1. Take a webmap offline (tested with a tiled raster basemap)
2. Open the "Basemap" pane and click on another basemap, e.. Bing Maps aerial
3. Try to switch back to the "default" basemap, only a gray map will be displayed.
--> I have not been able to find a way to switch back to the original basemap apart from opening another webmap first.

### Device Information
* Device: iPad 4 Mini
* OS Version: 11.2.6

**Comment by Kevin-GIS** [comment] 2018-04-20 18:29
Closing as duplicate of https://github.com/doug-m/CollectorAuroraTesting/issues/58

**Closed by Kevin-GIS** 2018-04-20 18:29 UTC
Labels: A-enhancement
