### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#30] opened 2018-04-05 18:53 UTC
### Issue

The app crashed while I was doing a combination of things:

1) Downloading a hosted feature service view from ArcGIS Online in an offline area
2) Adding a point via GPS averaging to the hosted feature service itself in connected mode

I couldn't reproduce the behavior doing those activities in conjunction again, but I was able to get the crash report, which I am emailing to the proper alias now.

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by miaogeng** [comment] 2018-04-25 18:05
Here is the issue crash log associated 
[Collector-2018-04-05-144101.ips.txt](https://github.com/doug-m/CollectorAuroraTesting/files/1948263/Collector-2018-04-05-144101.ips.txt)

**Comment by Kevin-GIS** [comment] 2018-10-02 00:49
Unable to reproduce the crash. Will gather more information if it happens again. Closing this issue.

**Closed by Kevin-GIS** 2018-10-02 00:49 UTC
Labels: A-bug, B - In Product Plan
