### ISSUE TITLE
C6 - Map with Vector Tiles couldn't take AdHoc Offline, which has already PrePlanned Areas

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#182] opened 2018-10-02 19:56 UTC
Dear Esri-Team,

Software: Collector (Aurora)
Version : 2440
iOS     : 12.0 - german
Device  : iPad Air 2

Description:

we publish from Pro a VectorTile and a Feature Service, configure for both the offline capabilities and also in the WebMap, where those layers are added.
The WebMap is shared to public so it's availibile for you:

http://austria.maps.arcgis.com/home/webmap/viewer.html?webmap=b680174feb024223847d6d175f2c06dc

We have no problem to configure two pre planned offline areas, which we could download. But when we create an AdHoc Offline Area we got the
message Export Tiles is not enabled, which is not clear to us, as the ProPlanned creation worked well.

If needed you could have the data - but I think Doug has it already from the past testing in spring 2018.

Gerhard "Luigi" Trichtl
[bug2.docx](https://github.com/doug-m/CollectorAuroraTesting/files/2439488/bug2.docx)

**Comment by miaogeng** [comment] 2018-10-02 21:21
@trichtl I saved as a new webmap but I can't reproduce the issue. Can you try to save as a new webmap to see if the issue still happens?

**Comment by trichtl** [comment] 2018-10-03 17:31
Hi @miaogeng - I did retest now without any Change on the webmap and services and it worked - it Looks like a restart of the App does also update the webmap Information correctly. As I had yesterday done a lot of changes on the webmap and Services after I had first open it on the device.

**Comment by miaogeng** [comment] 2018-10-04 17:56
Thanks for the reply. I will close it as not reproducible for now.

**Closed by miaogeng** 2018-10-04 17:56 UTC
Labels: A-bug, B - Dev Review

**Comment by trichtl** [comment] 2018-11-03 01:16
@miaogeng - thank tested now again with Build 2469 and it worked now as expected - Thanks for fixing
