### ISSUE TITLE
North arrow disappears and overlaps location button randomly

### ISSUE THREAD

**Issue by sbubka94** [doug-m/CollectorAuroraTesting#143] opened 2018-06-19 16:37 UTC
### Issue
The behavior is very inconsistent but the north arrow seems to sometime disappear entirely and other times, it overlaps the blue Location Me button. When it does disappear, it sometimes causes the map to no longer load and you have to restart the app. I've triggered this from zooming in/out, panning, and changing basemaps.

### Expected Behavior
I couldn't figure out if that north arrow even did anything. Is it supposed to just be an indicator of direction?

### Map and Credentials
Happened across multiple maps

### Steps to Reproduce

http://www.screencast.com/t/QyRORC6APZA

http://www.screencast.com/t/97wirat5a

### Device Information
* Device: iPhone 7+
* OS Version: iOS 11.4

**Comment by Kevin-GIS** [comment] 2018-06-25 23:21
Duplicate of https://github.com/doug-m/CollectorAuroraTesting/issues/96

**Closed** 2018-06-25 23:22 UTC
Labels: C-duplicate
