### ISSUE TITLE
Issue with hosted view in offline workflow

### ISSUE THREAD

**Issue by ThaoEss** [doug-m/CollectorAuroraTesting#217] opened 2019-03-13 23:18 UTC
### Issue

I have a hosted feature service set up with some nested relationship class: Hydrants > Inspection table > Violation table.
I created a hosted view from the feature service.
Create map offline package from AGOL.
Download map package.
Add a new point: Related records do not show. Only allow to fill in attributes for the point.

Want to test multiple views: unable to proceed.

1. Attempt: Collector crashed

2. Attempt: Collector doesn't allow the package to be downloaded.
3. Attempt: Exit out of Collector. Create a new package (2nd) with a different extent. Can download this one, yet the 1st package is still inaccessible.

Performance seems to be very unstable. After several use, attempt to open the 2nd map package and nothing displays. Sometimes clicking the map package doesn't open it at all.

### Map and Credentials

* Group Name: ESS_HolisticCollectorMarch13

* Map Name: view1only

### Device Information
* Device: Samsung galaxy 
* OS Version: 6.0.1

**Comment by Kevin-GIS** [comment] 2019-03-15 23:48
@ThaoEss Thank you for feedback.

I was able to reproduce the crashing behavior. It's due to the View2 hosted feature layer view being set to 'Add Only'. If it supported full editing, it wouldn't crash.

I logged this issue on our end. AF 654

**Comment by Kevin-GIS** [comment] 2019-08-07 02:02
This issue has been addressed and is no longer reproducible. 

Closing this one out.

**Closed by Kevin-GIS** 2019-08-07 02:02 UTC
Labels: A-bug, Android, C - implemented
