### ISSUE TITLE
Empty feature service download for Offline "On Demand" mode, Collector freeze if try and zoom first. 

### ISSUE THREAD

**Issue by mskinner123** [doug-m/CollectorAuroraTesting#203] opened 2018-10-03 21:27 UTC
### Issue
When trying to download a map using On Demand mode, if you try and pan/ zoom more than once it seems like Collector has a partial freeze. You can no longer pan/zoom around the map. Additionally clicking other buttons (ex. Download, Bookmarks > Default Map Extent) do not proceed to the expected behaviour.  For example clicking download does not change to the download screen and does not show that the map started downloading. Clicking the Default Map Extent does not zoom the map back to the previous extent.

Additionally, trying to adjust the Level of detail after that first pan/zoom also does not seem to have any effect. 
The cancel button takes you back to the previous screen, and the buttons for the other maps may or may not work (that portion is intermittent). i.e. sometimes I can click and access the other options, other times I cannot. 

To get Collector back up and running as expected I found I needed to close the app entirely. 

### Notes:
To avoid the issue, select the level of detail before panning and zooming. The default level of detail is set to "Room". 

Also tested on an iPad Air 2. Can't reproduce the issue. Details below:
- Same map, shared via group. 
- Other user on a different network and different device. 
- Doesn't have the issue.

### Expected Behaviour
Be able to adjust the level of detail after panning and zooming, or that after panning and zooming once you can continue to pan and zoom. 

### Map and Credentials
* Group Name: CollectorAuroraTesting
* Map Name: EmptyLayerMap2

### Steps to Reproduce
1. Open Collector and check you can see the "EmptyLayerMap2"
2. Click the options to take the map offline "Add Offline Area"
3. On the dialogue that pops up, Pan or Zoom 
4. Try and pan or zoom again - notice you cannot.
5. Try and download the map, return to default extent or adjust the level of detail and pan/zoom again.

### Device Information
Can reproduce the issue
* Device:  iPad Pro 2017 10.5 inch (iPad model: A1709)
* OS Version: 12

Can't reproduce the issue:
* Device: iPad Air 2 
* OS Version: 12

**Comment by Kevin-GIS** [comment] 2018-10-03 22:46
@mskinner123 I tested this issue on both an iPhone X and and an iPad Pro (13 inch) and was unable to reproduce this issue. 

Does it happen consistently on that device only?

If you try a different network connection does it work successfully?

Thanks

**Comment by mskinner123** [comment] 2018-10-04 03:37
Hi Kevin,

I'm glad to hear it wasn't reproducible on those devices! It was consistent on the one device (iPad Pro), but unfortunately I won't have access to that device for some time as it is a colleague's.

At this point, i'm not sure if the issue is specific to the device, or if Collector just needed to be uninstalled and re-installed.  Since we can't reproduce and I won't be able to access the device for a while, I'm not sure how much we can do in the meantime. If there's anything that might help in the meantime, let me know!

**Comment by xavierjunod** [comment] 2018-10-04 15:39
Hi Kevin, I was able to reproduce a similar issue using a bookmark. 

Look for the "Collector_testmap" in the "Holistic_testing" group

1.  create a bookmark to a pretty large area ( big city, state, etc.)
2. add a new offline area, make sure that the default is set to room
3. in the Add Offline Area menu, pick the bookmark (in my map, pick the "vancouver" bookmark
4. Collector will pan to this area and crash

This also happens are other large scale levels like "Small building"

Also tested on iPad pro with iOS11

**Comment by Kevin-GIS** [comment] 2018-10-04 17:50
Thanks for the information @mskinner123

**Comment by Kevin-GIS** [comment] 2018-10-04 17:54
Thanks for the information @xavierjunod 

I cannot reproduce this issue using my iPad. Could you please send a video of this issue happening on your end?

Also, could you please share the crash log from the iOS device?

Thanks

**Comment by Kevin-GIS** [comment] 2018-10-09 21:57
Hi @xavierjunod 

When you installed this holistic build, did you install on top of an existing build of Aurora, or was this a fresh install?

Can you still reproduce this issue?

Thanks

**Comment by xavierjunod** [comment] 2018-10-11 18:10
Hi Kevin, I installed it on the top of an existing one.  
I recorded this issue, see the .mov file in the zipped folder attached

[Hollistic testing Select BM crash.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2470127/Hollistic.testing.Select.BM.crash.zip)

**Comment by Kevin-GIS** [comment] 2018-10-31 23:51
@xavierjunod this issue is due to having Logging enabled in Settings when trying to perform the download. Disable logging, and this issue is not reproducible.

Logged SF 1291

**Comment by Kevin-GIS** [comment] 2018-11-13 00:46
This issue has been addressed. 

Closing this issue.

**Closed by Kevin-GIS** 2018-11-13 00:46 UTC
Labels: A-bug, B - In Product Plan
