### ISSUE TITLE
Remove area in offline mode causes a strange behavior

### ISSUE THREAD

**Issue by krithicakantharaj** [doug-m/CollectorAuroraTesting#82] opened 2018-05-10 19:04 UTC
### Issue
If there is only one offline area downloaded to the device and if the remove area option is used in offline mode, all maps disappear in collector. When you go back to online mode, the offline area is available to download in the webmap area. clicking on download takes you to the next page and displays the loading animation indefinately 

### Expected Behavior
the remove area should not cause this strange behavior 

### Map and Credentials
* Group Name: Aurora Holistic testing May 10
* Map Name: Aurora Test Map 2

### Steps to Reproduce
1. download lynn offline area to device
2. take device offline
3. in collector app, remove lynn area
4. go back online

Result: The offline area will be available to download as part of the webmaps. try to download the offline area and it displays loading indefinitely.

### Device Information
* Device: iphone 8
* OS Version: 11.3.1

**Comment by li2504** [comment] 2018-05-10 19:41
@Kevin-GIS Kevin, could you please try to repro this issue? I can't seem to reproduce it. In terms of "offline", I turn off Wi-Fi, my device has no data. Thank you.

**Comment by caro7202** [comment] 2018-05-10 21:34
We are aware if this issue. SF 742

**Comment by caro7202** [comment] 2018-06-19 18:44
Unable to reproduce with June holistic build. Closing this out.

**Closed by caro7202** 2018-06-19 18:44 UTC
Labels: A-bug, B - In Product Plan
