### ISSUE TITLE
Collector crashes after removing offline areas and refreshing

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#104] opened 2018-06-18 19:02 UTC
### Issue
Collector crashed after removing 2 of 2 offline areas for a map, then pulling to refresh the home screen on iOS. Attached crash log. 

[Collector-2018-06-18-115409.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2112608/Collector-2018-06-18-115409.zip)

### Map and Credentials

* Group Name: Collector Holistic 6/18
* Map Name: Zion_vector_streets

### Device Information
* Device: iPhone 6s
* OS Version: 11.3

**Comment by JCox-Williams** [comment] 2018-06-18 19:05
I experienced the same issue.

**Comment by Kevin-GIS** [comment] 2018-08-16 19:39
I am unable to reproduce this issue in the current Beta Build 2338. Closing this issue.

**Closed by Kevin-GIS** 2018-08-16 19:39 UTC
Labels: A-bug, B - Dev Review
