### ISSUE TITLE
GPS location feature malfunction

### ISSUE THREAD

**Issue by vugrant3** [doug-m/CollectorAuroraTesting#95] opened 2018-05-10 22:47 UTC
### Randomly activates gps locator

I scrolled over to City of RC to test some data and it would randomly bring me back to the esri campus.

### Expected Behavior
Should only do that when I hit the button

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device:  iPad mini
* OS Version:  iOS 11.3.1

**Comment by Kevin-GIS** [comment] 2018-05-17 18:54
@vugrant3 could you please elaborate on your workflow?

Did you pan the map before clicking the '+' button and choosing an editing template and it snapped you back to your current location?

Were you indoors or outside?

**Comment by kyliedonia** [comment] 2018-05-17 18:57
@Kevin-GIS I asked the same thing on the day of testing, sorry I forgot to post his answer here. He panned away, and wasn't initiating a collection when he'd be panned back.

**Comment by Kevin-GIS** [comment] 2018-05-18 19:05
I tested the workflow, but cannot reproduce the issue. 

@vugrant3 could you please provide the steps to reproduce this issue?

**Comment by Kevin-GIS** [comment] 2018-05-18 22:57
I am going to close this issue for the time being. Will reopen once more information is available or is reproducible.

**Closed by Kevin-GIS** 2018-05-18 22:57 UTC
Labels: C-not reproducible
