### ISSUE TITLE
Arcade Expression in Related Table

### ISSUE THREAD

**Issue by dking159** [doug-m/CollectorAuroraTesting#110] opened 2018-06-18 19:43 UTC
### Issue
Created an Arcade expression in a related table and it causes Collector to freeze when it tries to display the calculated field.

Expression: 
(29.83 * 0.9) * pow(2.5,2) * sqrt($feature.FLOWHYDPITOPSI)

### Map and Credentials

* Group Name: 
* Map Name:

### Steps to Reproduce
1. Add expression to the related record on the web map
2. View related records in web map and calculation is shown correctly.
3. View same location in Collector.
4. Show related records
5. Scroll down to the bottom of the related records.  Right before you can see the field it freezes collector.

### Device Information
* Device:
* OS Version:

**Comment by Kevin-GIS** [comment] 2018-06-19 16:00
Hi @dking159 

Would you be able to share the map with me?

**Comment by dking159** [comment] 2018-06-19 16:02
Sorry the map service we are using is behind our firewall.  Can we do a screen share?


Dennis

________________________________

**Comment by Kevin-GIS** [comment] 2018-06-19 16:09
@dking159 No worries. I will try using my own data, I don't think it matters what the specific expression is. But if I can't reproduce it, then I will reach out and we can setup a time to do the screen share. 

Thanks

**Comment by Kevin-GIS** [comment] 2018-06-19 18:43
Logged SF 975

**Comment by Kevin-GIS** [comment] 2018-10-02 00:12
This issue has been addressed. Closing this issue.

**Closed by Kevin-GIS** 2018-10-02 00:12 UTC
Labels: A-bug, B - In Product Plan
