### ISSUE TITLE
C24 - Download Fails without error, which worked in previous Testing Event

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#166] opened 2018-08-22 18:03 UTC
Dear Esri-Team,

Software: Collector
Verion  : Build 2358
OS      : iOS 11.4.1, iPad Air 2

Description:

we have a WebMap with some Arcade Labeling setup, displays fine in Pro and after publish to Online it shows in Collector.

When taking now an area offline it starts and finally crashes Collector - as I remember this works at the last Testing event

Attached the data and screendumps to reproduce the problem.

Best regards,

Gerhard "Luigi" Trichtl
[C24.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2311488/C24.zip)

**Comment by Kevin-GIS** [comment] 2018-08-23 17:49
Thanks for the feedback @trichtl 

Logged SF 1115

**Comment by Kevin-GIS** [comment] 2018-09-20 20:27
@trichtl the crash is no longer reproducible in the latest beta version 2418. 

This issue is very similar to https://github.com/doug-m/CollectorAuroraTesting/issues/13 with the same 'Failed to create replica' error that is logged with AGOL. 

Closing this issue since the crashing is fixed.

**Closed by Kevin-GIS** 2018-09-20 20:27 UTC
Labels: A-bug, B - In Product Plan

**Comment by trichtl** [comment] 2018-10-02 17:32
HI @Kevin-GIS, - yes it Looks similar to #13 - one idea might be that the layername contains Special characters like äöüäöü - also this layer contains those types of characters. Those are comon in german speeking Country - I would assume that within other languages (spanish, French) there might be similar Problems - in case #53 we have at the layername no Special characters, just on the Service and there it seems to work.

Gerhard "Luigi" Trichtl

**Comment by Kevin-GIS** [comment] 2018-10-02 17:37
@trichtl thanks for the testing feedback.

**Comment by trichtl** [comment] 2018-11-02 22:09
Hi @Kevin-GIS - as an related case was fixed - I reseted, but this still Fails just after a view seconds. (approx. 12.5 % of the circle)
